### ISSUE TITLE
FileNotFoundError when running wa_kdbe.py, apt-get command not found | macOS

### ISSUE THREAD

**Issue by shloak17107** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#35]
**Describe the bug**
FileNotFoundError for `adb.exe` when running `wa_kdbe.py`

**To Reproduce**
1. Device connected via cable and USB debugging enabled
2. Run `python3 wa_kdbe.py --allow-reboot`
3. See error

**Terminal output**
```
sh: /Users/shloak/Downloads/WhatsApp-Key-Database-Extractorbinadb.exe: No such file or directory
sh: /Users/shloak/Downloads/WhatsApp-Key-Database-Extractorbinadb.exe: No such file or directory
Traceback (most recent call last):
  File "wa_kdbe.py", line 228, in <module>
    ADBSerialId = deviceId.init()
  File "/Users/shloak/Downloads/WhatsApp-Key-Database-Extractor/helpers/ADBDeviceSerialId.py", line 29, in init
    proc = sp.Popen(cmd.split(), stdin=sp.PIPE, stdout=sp.PIPE,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shloak/Downloads/WhatsApp-Key-Database-Extractor\\bin\\adb.exe'
```

**Desktop:**
 - OS: macOS Big Sur

**Smartphone:**
 - Device: Motorola G4 Plus
 - Android Nougat
 - Version 7.0

**Comment by shloak17107** [comment]
One more thing...

Since I'm using a Mac, I don't think I have the `apt-get` command. So, I'm not able to install the dependencies given in the `linux_dependencies.sh` file. I get the following terminal output:

```
Installing dependencies... Hold on.
Updating system.
./bin/linux_dependencies.sh: line 6: apt-get: command not found
Installing packages.
./bin/linux_dependencies.sh: line 13: apt-get: command not found
./bin/linux_dependencies.sh: line 13: apt-get: command not found
./bin/linux_dependencies.sh: line 13: apt-get: command not found
./bin/linux_dependencies.sh: line 13: apt-get: command not found
./bin/linux_dependencies.sh: line 13: apt-get: command not found
./bin/linux_dependencies.sh: line 13: apt-get: command not found
Done installing packages. Cheers.
```

**Comment by YuvrajRaghuvanshiS** [comment]
I never got a chance to test this on mac this is why these problems are here. You can solve second one by changing `apt-get` to `brew` in linux_dependencies.sh

**Comment by YuvrajRaghuvanshiS** [comment]
Do a quick 
```
git pull origin
git checkout issues/35
```

Here try to install dependencies again, however you need homebrew on your machine for that. Once they get install run program.

**Comment by YuvrajRaghuvanshiS** [comment]
Problem fixed, 
Rebase and merged.

**Comment by YuvrajRaghuvanshiS** [comment]
Wrong reference.
