### ISSUE TITLE
Crashes silently after the banner (while trying to CheckJava)

### ISSUE THREAD

**Issue by nathanvogel** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#66]
Hi, thanks for the tool, looks great!

**Describe the bug**
The program crashes silently when trying to check whether Java is installed.

**To Reproduce**
1. run 'python.exe .\wa_kdbe.py' or double click the file
2. Quits 1 second after the banner

**Expected behavior**
Shows a crash error or shows me whether Java is installed or not. 

**Screenshots**
Here I have modified the script with print calls as on the screenshot to find out which line is responsible for the crash.
![image](https://user-images.githubusercontent.com/3106715/118363268-d5663f80-b593-11eb-91df-3c43e51af54b.png)

**Desktop:**
 - OS: [e.g. Windows 10]

**First run log**

```
First run : Auto installing python requirements.

Collecting packaging
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 2.5 MB/s
Collecting psutil
  Downloading psutil-5.8.0-cp39-cp39-win_amd64.whl (246 kB)
     |████████████████████████████████| 246 kB 3.3 MB/s
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB ...
Collecting tqdm
  Downloading tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 2.0 MB/s
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB ...
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB ...
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB ...
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB ...
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB ...
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Installing collected packages: urllib3, pyparsing, idna, chardet, certifi, tqdm, termcolor, requests, psutil, packaging
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] Le fichier spécifié est introuvable: 'c:\\python39\\Scripts\\chardetect.exe' -> 'c:\\python39\\Scripts\\chardetect.exe.deleteme'

Collecting termcolor
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Installing collected packages: termcolor
    Running setup.py install for termcolor ... done
Successfully installed termcolor-1.1.0
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting tqdm
  Using cached tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
Requirement already satisfied: pyparsing>=2.0.2 in c:\python39\lib\site-packages (from packaging) (2.4.7)
Requirement already satisfied: idna<3,>=2.5 in c:\python39\lib\site-packages (from requests) (2.10)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\python39\lib\site-packages (from requests) (4.0.0)
Installing collected packages: certifi, tqdm, requests, packaging
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] Le fichier spécifié est introuvable: 'c:\\python39\\Scripts\\tqdm.exe' -> 'c:\\python39\\Scripts\\tqdm.exe.deleteme'

Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: tqdm in c:\python39\lib\site-packages (4.60.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\python39\lib\site-packages (from packaging) (2.4.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\python39\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\python39\lib\site-packages (from requests) (2.10)
Installing collected packages: requests, packaging
Successfully installed packaging-20.9 requests-2.25.1
cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée. (10061)
* daemon not running; starting now at tcp:5037
* daemon started successfully
Traceback (most recent call last):
  File "C:\Users\nathan\bin\WhatsApp-Key-Database-Extractor\wa_kdbe.py", line 309, in <module>
    ADBSerialId = deviceId.init()
  File "C:\Users\nathan\bin\WhatsApp-Key-Database-Extractor\helpers\ADBDeviceSerialId.py", line 43, in init
    CustomPrint(
  File "C:\Users\nathan\bin\WhatsApp-Key-Database-Extractor\helpers\CustomCI.py", line 21, in CustomPrint
    cprint(time + textToPrint, color, attrs=attr)
NameError: name 'cprint' is not defined
```

**Comment by YuvrajRaghuvanshiS** [comment]
Working on it.

**Comment by nathanvogel** [comment]
Thanks! I just did a fresh clone and I'm not getting the error anymore!

**Comment by YuvrajRaghuvanshiS** [comment]
So is it working?

**Comment by nathanvogel** [comment]
Looks like it! I think the first install got corrupted. 
As far as I'm concerned you can close :)

**Comment by YuvrajRaghuvanshiS** [comment]
Cool...

**Comment by nathanvogel** [comment]
Just wanted to say thank you! It worked :D

**Comment by YuvrajRaghuvanshiS** [comment]
😆 It's awesome it's it!
