### ISSUE TITLE
Getting exception after entering user and password

### ISSUE THREAD

**Issue by Mustafa01-Ali** [YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor#92]
Could not unpack "tmp/whatsapp.ab"
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/nick/abe/Main : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:125)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:263)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:198)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:247)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

**Comment by YuvrajRaghuvanshiS** [comment]
Ask [here](https://github.com/nelenkov/android-backup-extractor/). Maybe try to download latest abe.jar from the above link and save that to WA-KDBE/bin folder.

------- Original Message -------

**Comment by Mustafa01-Ali** [comment]
I downloaded the latest code yesterday itself. Please help buddy.

logs for reference.......................

[Monday 28/03/2022, 22:26:39] Found Java v1.7.0-ea installed on system. Continuing...

[Monday 28/03/2022, 22:26:39] Turned off wifi and mobile data...
[Monday 28/03/2022, 22:26:39] Please read above instructions carefully ↑ . Continue? (default y): y


[Monday 28/03/2022, 22:26:39] If you haven't already, it is adviced to take a WhatsApp chat backup by going to "WhatsApp settings → Chat Settings → Chat Backup". Hit "Enter" key to continue.
[Monday 28/03/2022, 22:26:39] Connected to CPH2179
[Monday 28/03/2022, 22:26:39] WhatsApp v2.22.6.72 installed on device
[Monday 28/03/2022, 22:26:39] Found legacy WhatsApp V2.11.431 apk in "helpers" folder
[Monday 28/03/2022, 22:26:39] Backing up WhatsApp 2.22.6.72 apk, the one installed on device to "/data/local/tmp/WhatsAppbackup.apk" in your phone.
[Monday 28/03/2022, 22:26:39] Apk backup is completed.
[Monday 28/03/2022, 22:26:39] Uninstalling WhatsApp, skipping data.
[Monday 28/03/2022, 22:26:39] Uninstalled.
[Monday 28/03/2022, 22:26:39] Installing legacy WhatsApp V2.11.431, hold tight now.
[Monday 28/03/2022, 22:26:39] Installation Complete.
[Monday 28/03/2022, 22:26:39] Starting: Intent { cmp=com.whatsapp/.Main }
[Monday 28/03/2022, 22:26:39] Running legacy WhatsApp, it may crash, do not check for updates if it prompts.
[Monday 28/03/2022, 22:26:39] Folder tmp/ already exists.
[Monday 28/03/2022, 22:26:39] Backing up WhatsApp data as "tmp/whatsapp.ab". May take time, don't panic.
WARNING: adb backup is deprecated and may be removed in a future release
Now unlock your device and confirm the backup operation...
[Monday 28/03/2022, 22:26:39] Done backing up data. Size: 13597285 bytes.
[Monday 28/03/2022, 22:26:39] Reinstalling original WhatsApp.
[Monday 28/03/2022, 22:26:39] Reinstallation complete.


[Monday 28/03/2022, 22:26:39] Our work with device has finished, it is safe to remove it now.


[Monday 28/03/2022, 22:26:39] Found "whatsapp.ab" in "tmp" folder. Continuing... Size: 13597285 bytes.
[Monday 28/03/2022, 22:26:39] Enter a name for this user (default "user").: user
[Monday 28/03/2022, 22:26:39] Enter same password which you entered on device when prompted earlier.: 
[Monday 28/03/2022, 22:26:39] Could not unpack "tmp/whatsapp.ab"
[Monday 28/03/2022, 22:26:39] Exception in thread "main" java.lang.UnsupportedClassVersionError: org/nick/abe/Main : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:125)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:263)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:198)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:247)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)


[Monday 28/03/2022, 22:26:39] Exiting...
[Monday 28/03/2022, 22:26:39] Turn off USB debugging [and USB debugging (Security Settings)] if you're done.
[Monday 28/03/2022, 22:26:39] Hit "Enter" key to continue....
